import type { FlexibleContent } from '@/blocks/types'

// Fallback data cho law template khi WP chưa có ACF flexible content
// Dev thay nội dung này theo brief của từng client

export const LAW_HOME_FALLBACK: FlexibleContent = [
  {
    acf_fc_layout: 'hero',
    slides: [
      {
        badge_text: '⚖️ Hơn 10 Năm Kinh Nghiệm Pháp Lý',
        headline: 'Giải Pháp Pháp Lý Toàn Diện Cho',
        headline_highlight: 'Doanh Nghiệp',
        slogan: 'Minh bạch – Chuyên nghiệp – Tận tâm',
        description:
          'Đồng hành cùng hàng trăm doanh nghiệp trong hành trình thành lập, vận hành và phát triển bền vững. Chi phí tối ưu, xử lý nhanh chóng.',
        cta_primary_text: 'Tư Vấn Miễn Phí',
        cta_primary_link: '#contact',
        cta_secondary_text: 'Xem Dịch Vụ →',
        cta_secondary_link: '/dich-vu',
      },
      {
        badge_text: '🏢 Thành Lập Doanh Nghiệp Nhanh',
        headline: 'Hoàn Thiện Hồ Sơ Trong',
        headline_highlight: '1–3 Ngày',
        slogan: 'Trọn gói – Không phát sinh chi phí ẩn',
        description:
          'Thành lập công ty TNHH, cổ phần, hộ kinh doanh và doanh nghiệp FDI. Đăng ký MST, con dấu, tài khoản ngân hàng trọn gói.',
        cta_primary_text: 'Thành Lập Ngay',
        cta_primary_link: '/dich-vu/thanh-lap-tnhh',
        cta_secondary_text: 'Xem Gói Dịch Vụ',
        cta_secondary_link: '/dich-vu',
      },
      {
        badge_text: '🔒 Bảo Hộ Thương Hiệu & SHTT',
        headline: 'Đăng Ký Độc Quyền',
        headline_highlight: 'Nhãn Hiệu Toàn Quốc',
        slogan: 'Bảo vệ tài sản trí tuệ từ ngày đầu',
        description:
          'Tra cứu, đánh giá khả năng đăng ký và nộp đơn tại NOIP. Theo dõi và xử lý tranh chấp nhãn hiệu trên toàn quốc.',
        cta_primary_text: 'Đăng Ký Bảo Hộ',
        cta_primary_link: '/dich-vu/bao-ho-thuong-hieu',
        cta_secondary_text: 'Tìm Hiểu Thêm',
        cta_secondary_link: '/dich-vu',
      },
    ],
    stats: [
      { value: '500+', label: 'DN thành lập' },
      { value: '10+', label: 'Năm kinh nghiệm' },
      { value: '98%', label: 'Khách hàng hài lòng' },
      { value: '50+', label: 'Chuyên gia pháp lý' },
    ],
    checklist: [
      { text: 'Thành lập doanh nghiệp trọn gói' },
      { text: 'Tư vấn thuế & kế toán chuyên sâu' },
      { text: 'Chứng thư số & hóa đơn điện tử' },
      { text: 'Đăng ký bảo hiểm xã hội nhanh chóng' },
      { text: 'Bảo vệ thương hiệu & sở hữu trí tuệ' },
    ],
    show_stats_card: true,
    autoplay_delay: 5000,
  },
  {
    acf_fc_layout: 'trust_bar',
    items: [
      { text: 'Top 10 Dịch Vụ Pháp Lý TP.HCM' },
      { text: 'ISO 9001:2015 Chứng Nhận' },
      { text: 'Xử Lý Hồ Sơ 1–3 Ngày' },
      { text: 'Cam Kết Bảo Mật Tuyệt Đối' },
      { text: 'Hỗ Trợ 7 Ngày / Tuần' },
    ],
  },
  {
    acf_fc_layout: 'services_grid',
    section_label: 'Dịch Vụ Pháp Lý',
    section_title: 'Thành Lập & Vận Hành Doanh Nghiệp',
    section_desc: 'Chúng tôi đồng hành từ bước đầu thành lập đến vận hành và phát triển bền vững',
    dark_background: false,
    columns: 3,
    services: [
      {
        title: 'Thành Lập Công Ty TNHH',
        description: 'Tư vấn và thực hiện toàn bộ thủ tục đăng ký thành lập công ty TNHH 1 hoặc 2 thành viên.',
        features: ['Soạn thảo điều lệ công ty', 'Đăng ký MST, con dấu pháp nhân', 'Hỗ trợ sau thành lập trọn gói'],
        link_text: 'Xem chi tiết',
        link_url: '/dich-vu/thanh-lap-tnhh',
      },
      {
        title: 'Thành Lập Công Ty Cổ Phần',
        description: 'Thủ tục thành lập công ty cổ phần nhanh chóng, đúng quy định pháp luật hiện hành.',
        features: ['Tư vấn cơ cấu cổ đông tối ưu', 'Soạn thảo quy chế nội bộ', 'Phát hành cổ phần đúng luật'],
        link_text: 'Xem chi tiết',
        link_url: '/dich-vu/thanh-lap-co-phan',
      },
      {
        title: 'Tư Vấn Thuế & Kế Toán',
        description: 'Dịch vụ kế toán thuế chuyên nghiệp, giúp doanh nghiệp tối ưu chi phí và tuân thủ pháp luật.',
        features: ['Khai thuế hàng tháng/quý', 'Quyết toán thuế cuối năm', 'Rà soát sổ sách kế toán'],
        link_text: 'Xem chi tiết',
        link_url: '/dich-vu/ke-toan-thue',
      },
      {
        title: 'DN Vốn Đầu Tư Nước Ngoài',
        description: 'Tư vấn và hỗ trợ thành lập doanh nghiệp FDI, xin giấy chứng nhận đăng ký đầu tư.',
        features: ['Xin GCNĐT / GPKD cho FDI', 'Tư vấn ngành nghề có điều kiện', 'Kết nối đối tác địa phương'],
        link_text: 'Xem chi tiết',
        link_url: '/dich-vu/fdi',
      },
      {
        title: 'Bảo Hộ Thương Hiệu',
        description: 'Đăng ký độc quyền nhãn hiệu, bảo vệ tài sản trí tuệ cho doanh nghiệp.',
        features: ['Tra cứu & đánh giá khả năng đăng ký', 'Nộp đơn tại NOIP', 'Theo dõi và xử lý tranh chấp'],
        link_text: 'Xem chi tiết',
        link_url: '/dich-vu/bao-ho-thuong-hieu',
      },
      {
        title: 'Giải Thể Doanh Nghiệp',
        description: 'Hỗ trợ thủ tục giải thể, tạm ngừng kinh doanh nhanh chóng, đúng quy trình pháp luật.',
        features: ['Tư vấn phương án giải thể tối ưu', 'Xử lý công nợ, thuế còn tồn', 'Hoàn tất thủ tục với cơ quan nhà nước'],
        link_text: 'Xem chi tiết',
        link_url: '/dich-vu/giai-the',
      },
    ],
  },
  {
    acf_fc_layout: 'two_column',
    layout: 'image_right',
    dark_background: false,
    section_label: 'Tại Sao Chọn Chúng Tôi',
    section_title: 'Cam Kết Chất Lượng Dịch Vụ Hàng Đầu',
    section_desc: 'Với đội ngũ chuyên gia giàu kinh nghiệm, chúng tôi cung cấp giải pháp pháp lý toàn diện, minh bạch và hiệu quả cho mọi doanh nghiệp.',
    features: [
      { title: 'Chuyên gia pháp lý kinh nghiệm', description: 'Đội ngũ 50+ luật sư và chuyên gia kế toán với hơn 10 năm kinh nghiệm thực chiến.' },
      { title: 'Xử lý nhanh chóng', description: 'Cam kết hoàn thành hồ sơ thành lập doanh nghiệp trong 1–3 ngày làm việc.' },
      { title: 'Chi phí tối ưu', description: 'Báo giá minh bạch, trọn gói — không phát sinh chi phí ẩn.' },
      { title: 'Hỗ trợ sau dịch vụ', description: 'Đồng hành cùng doanh nghiệp 12 tháng sau thành lập miễn phí.' },
    ],
    badge_number: '10+',
    badge_label: 'Năm kinh nghiệm',
  },
  {
    acf_fc_layout: 'team_grid',
    section_label: 'Đội Ngũ Của Chúng Tôi',
    section_title: 'Chuyên Gia Pháp Lý Hàng Đầu',
    section_desc: 'Đội ngũ giàu kinh nghiệm, tâm huyết với nghề',
    dark_background: true,
    members: [
      { name: 'Nguyễn Văn A', role: 'CEO & Founder', description: 'Hơn 15 năm kinh nghiệm tư vấn pháp lý doanh nghiệp' },
      { name: 'Trần Thị B', role: 'Trưởng phòng Pháp lý', description: 'Chuyên gia về luật doanh nghiệp và đầu tư nước ngoài' },
      { name: 'Lê Văn C', role: 'Kế toán trưởng', description: 'Chuyên gia thuế và tài chính doanh nghiệp' },
      { name: 'Phạm Thị D', role: 'Luật sư tư vấn', description: 'Chuyên về sở hữu trí tuệ và thương hiệu' },
    ],
  },
  {
    acf_fc_layout: 'clients_logos',
    section_title: 'Khách hàng tin tưởng',
    dark_background: false,
    clients: [
      { name: 'Công ty TNHH ABC' },
      { name: 'Tập đoàn XYZ' },
      { name: 'Cty CP Đầu Tư 123' },
      { name: 'Startup Tech VN' },
      { name: 'Nhà Hàng Sài Gòn' },
      { name: 'Cty BĐS Việt' },
      { name: 'Chuỗi F&B Happy' },
      { name: 'DN FDI Korea' },
    ],
  },
  {
    acf_fc_layout: 'testimonials',
    section_label: 'Khách Hàng Nói Gì',
    section_title: 'Niềm Tin Được Xây Dựng Qua Từng Hồ Sơ',
    dark_background: true,
    testimonials: [
      {
        quote: 'Công ty hỗ trợ mình thành lập công ty TNHH chỉ trong 2 ngày làm việc. Toàn bộ thủ tục được xử lý trọn gói, không phát sinh thêm bất kỳ chi phí nào so với báo giá ban đầu. Rất chuyên nghiệp và đáng tin cậy.',
        author_name: 'Nguyễn Minh Tuấn',
        author_company: 'CEO, Công ty TNHH Thương Mại Minh Tuấn',
        rating: 5,
      },
      {
        quote: 'Là doanh nghiệp FDI, chúng tôi cần đơn vị tư vấn hiểu rõ luật đầu tư nước ngoài. Đội ngũ ở đây xử lý hồ sơ GCNĐT rất bài bản, tư vấn tận tình từng bước. Chúng tôi đã tin tưởng giao phó hoàn toàn.',
        author_name: 'Kim Ji-Hoon',
        author_company: 'Giám đốc, Korea Tech Vietnam Co., Ltd',
        rating: 5,
      },
      {
        quote: 'Dịch vụ kế toán thuế hàng tháng của công ty giúp chúng tôi luôn tuân thủ đúng hạn, không lo bị phạt. Đặc biệt trong mùa quyết toán năm, nhóm kế toán làm việc rất hiệu quả và phản hồi nhanh.',
        author_name: 'Trần Thị Lan Anh',
        author_company: 'Giám đốc Tài chính, Chuỗi F&B Ngon House',
        rating: 5,
      },
      {
        quote: 'Nhờ đăng ký bảo hộ nhãn hiệu kịp thời, thương hiệu của chúng tôi đã được bảo vệ trước một đối thủ có hành vi xâm phạm. Đội pháp lý xử lý tranh chấp rất sắc bén và bảo vệ lợi ích của chúng tôi đến cùng.',
        author_name: 'Lê Hoàng Phúc',
        author_company: 'Founder, Startup EduTech VN',
        rating: 5,
      },
    ],
  },
  {
    acf_fc_layout: 'faq_accordion',
    section_label: 'FAQ',
    section_title: 'Câu Hỏi Thường Gặp',
    section_desc: 'Giải đáp những thắc mắc phổ biến nhất của khách hàng',
    dark_background: false,
    faqs: [
      { question: 'Thành lập công ty TNHH mất bao lâu?', answer: 'Thông thường từ 3–5 ngày làm việc kể từ khi nộp hồ sơ đầy đủ. Chúng tôi cam kết hoàn thành trong 1–3 ngày với gói dịch vụ nhanh.' },
      { question: 'Chi phí thành lập công ty bao nhiêu?', answer: 'Chi phí thành lập công ty TNHH trọn gói từ 1.500.000đ – 3.000.000đ tùy loại hình và ngành nghề. Liên hệ để nhận báo giá chính xác.' },
      { question: 'Cần những giấy tờ gì để thành lập công ty?', answer: 'CMND/CCCD của tất cả thành viên/cổ đông, địa chỉ trụ sở, ngành nghề kinh doanh, vốn điều lệ. Chúng tôi sẽ hướng dẫn chi tiết trong buổi tư vấn đầu tiên.' },
      { question: 'Có thể thành lập công ty khi đang làm nhà nước không?', answer: 'Cán bộ công chức, viên chức nhà nước không được tham gia thành lập và quản lý doanh nghiệp theo Luật phòng chống tham nhũng. Tuy nhiên có thể góp vốn với tỷ lệ nhất định.' },
      { question: 'Dịch vụ kế toán thuế hàng tháng có những gì?', answer: 'Bao gồm: Khai báo thuế GTGT, TNCN hàng tháng; lập báo cáo tài chính quý; quyết toán thuế năm; tư vấn thuế thường xuyên; hỗ trợ kiểm tra thuế khi cần.' },
      { question: 'Tôi có thể thay đổi ngành nghề kinh doanh sau khi thành lập không?', answer: 'Hoàn toàn có thể. Thủ tục thay đổi GPĐKKD thường mất 3–7 ngày. Chúng tôi hỗ trợ trọn gói thủ tục này với chi phí hợp lý.' },
    ],
  },
  {
    acf_fc_layout: 'latest_posts',
    section_label: 'Kiến Thức Pháp Lý',
    section_title: 'Tin Tức & Cập Nhật Pháp Luật',
    section_desc: 'Theo dõi những thay đổi pháp lý mới nhất ảnh hưởng đến doanh nghiệp của bạn',
    dark_background: false,
    posts_count: 4,
    view_all_text: 'Xem tất cả tin tức',
    view_all_link: '/tin-tuc',
  },
  {
    acf_fc_layout: 'cta_banner',
    headline: 'Sẵn Sàng Bắt Đầu Hành Trình Kinh Doanh?',
    description: 'Liên hệ ngay hôm nay để nhận tư vấn miễn phí từ đội ngũ chuyên gia của chúng tôi.',
    cta_primary_text: 'Tư Vấn Miễn Phí Ngay',
    cta_primary_link: '#contact',
    cta_secondary_text: 'Gọi Hotline',
    cta_secondary_link: 'tel:19001234',
    dark_background: true,
  },
  {
    acf_fc_layout: 'contact_form',
    section_label: 'Liên Hệ',
    section_title: 'Đăng ký tư vấn miễn phí',
    dark_background: true,
  },
]
