import type { FlexibleContent } from '@/blocks/types'

export const LAW_SERVICES_FALLBACK: FlexibleContent = [
  {
    acf_fc_layout: 'hero',
    slides: [
      {
        badge_text: '⚖️ Dịch Vụ Pháp Lý',
        headline: 'Giải Pháp Toàn Diện Cho',
        headline_highlight: 'Mọi Doanh Nghiệp',
        slogan: 'Từ thành lập đến vận hành — chúng tôi lo trọn',
        description:
          'Chúng tôi cung cấp đầy đủ các dịch vụ pháp lý, kế toán và bảo hộ thương hiệu với chi phí tối ưu và tiến độ nhanh chóng.',
        cta_primary_text: 'Tư Vấn Ngay',
        cta_primary_link: '/lien-he',
        cta_secondary_text: 'Xem Bảng Giá →',
        cta_secondary_link: '#services',
      },
    ],
    stats: [
      { value: '6', label: 'Nhóm dịch vụ' },
      { value: '500+', label: 'Hồ sơ hoàn thành' },
      { value: '1–3', label: 'Ngày xử lý' },
      { value: '100%', label: 'Cam kết hoàn tiền' },
    ],
    checklist: [
      { text: 'Không phát sinh chi phí ẩn' },
      { text: 'Đội ngũ 50+ chuyên gia' },
      { text: 'Hỗ trợ sau dịch vụ 12 tháng' },
      { text: 'Cam kết bảo mật tuyệt đối' },
    ],
    show_stats_card: true,
  },
  {
    acf_fc_layout: 'trust_bar',
    items: [
      { text: 'Thành Lập Doanh Nghiệp' },
      { text: 'Kế Toán & Thuế' },
      { text: 'Bảo Hộ Thương Hiệu' },
      { text: 'Doanh Nghiệp FDI' },
      { text: 'Giải Thể & Tái Cơ Cấu' },
    ],
  },
  {
    acf_fc_layout: 'services_grid',
    section_label: 'Thành Lập Doanh Nghiệp',
    section_title: 'Khởi Nghiệp Đúng Hướng, Nhanh Chóng & Đúng Luật',
    section_desc: 'Trọn gói từ tư vấn loại hình phù hợp đến hoàn tất đăng ký kinh doanh',
    dark_background: false,
    columns: 3,
    services: [
      {
        title: 'Công Ty TNHH 1 Thành Viên',
        description: 'Phù hợp cá nhân khởi nghiệp, toàn quyền quyết định và chịu trách nhiệm hữu hạn trong phạm vi vốn góp.',
        features: ['Thời gian: 3–5 ngày làm việc', 'Hỗ trợ đăng ký con dấu & MST', 'Tư vấn vốn điều lệ phù hợp ngành'],
        link_text: 'Xem gói dịch vụ',
        link_url: '/dich-vu/thanh-lap-tnhh-1tv',
      },
      {
        title: 'Công Ty TNHH 2 Thành Viên+',
        description: 'Lý tưởng cho mô hình hợp tác kinh doanh, phân chia quyền lợi và nghĩa vụ theo tỷ lệ vốn góp.',
        features: ['Soạn thảo điều lệ & thỏa thuận cổ đông', 'Đăng ký thay đổi thành viên khi cần', 'Tư vấn quản trị nội bộ'],
        link_text: 'Xem gói dịch vụ',
        link_url: '/dich-vu/thanh-lap-tnhh-2tv',
      },
      {
        title: 'Công Ty Cổ Phần',
        description: 'Mô hình linh hoạt, phù hợp doanh nghiệp có kế hoạch mở rộng quy mô và huy động vốn từ nhiều nhà đầu tư.',
        features: ['Phát hành cổ phần đúng luật', 'Soạn thảo quy chế quản trị HĐQT', 'Tư vấn tối ưu cơ cấu cổ đông'],
        link_text: 'Xem gói dịch vụ',
        link_url: '/dich-vu/thanh-lap-co-phan',
      },
    ],
  },
  {
    acf_fc_layout: 'services_grid',
    section_label: 'Kế Toán & Thuế',
    section_title: 'Dịch Vụ Kế Toán Thuế Trọn Gói',
    section_desc: 'Để bạn tập trung vào kinh doanh, chúng tôi lo phần còn lại',
    dark_background: true,
    columns: 3,
    services: [
      {
        title: 'Kế Toán Thuế Hàng Tháng',
        description: 'Khai báo thuế GTGT, TNCN đầy đủ, đúng hạn. Lập và nộp báo cáo theo quy định mới nhất.',
        features: ['Khai thuế GTGT, TNCN hàng tháng/quý', 'Hóa đơn điện tử & chứng từ đầu vào', 'Báo cáo tài chính theo chuẩn VAS'],
        link_text: 'Xem chi tiết',
        link_url: '/dich-vu/ke-toan-thue-hang-thang',
      },
      {
        title: 'Quyết Toán Thuế Năm',
        description: 'Lập báo cáo tài chính năm, khai quyết toán thuế TNDN và TNCN chính xác, tối ưu số thuế phải nộp.',
        features: ['Rà soát sổ sách toàn bộ năm tài chính', 'Tối ưu chi phí hợp lệ được khấu trừ', 'Xử lý kiểm tra thuế nếu phát sinh'],
        link_text: 'Xem chi tiết',
        link_url: '/dich-vu/quyet-toan-thue',
      },
      {
        title: 'Hoàn Thuế GTGT',
        description: 'Hỗ trợ lập hồ sơ hoàn thuế GTGT cho doanh nghiệp xuất khẩu và đầu tư tài sản cố định lớn.',
        features: ['Chuẩn bị hồ sơ hoàn thuế đầy đủ', 'Theo dõi tiến độ hoàn trả từ cục thuế', 'Xử lý yêu cầu bổ sung hồ sơ'],
        link_text: 'Xem chi tiết',
        link_url: '/dich-vu/hoan-thue',
      },
    ],
  },
  {
    acf_fc_layout: 'services_grid',
    section_label: 'Bảo Hộ Thương Hiệu & SHTT',
    section_title: 'Bảo Vệ Tài Sản Trí Tuệ Của Bạn',
    section_desc: 'Nhãn hiệu, bằng sáng chế, bản quyền — chúng tôi bảo vệ toàn diện',
    dark_background: false,
    columns: 3,
    services: [
      {
        title: 'Đăng Ký Nhãn Hiệu Trong Nước',
        description: 'Tra cứu, đánh giá và nộp đơn đăng ký nhãn hiệu tại Cục SHTT Việt Nam.',
        features: ['Tra cứu khả năng đăng ký miễn phí', 'Nộp đơn và theo dõi hồ sơ', 'Thời gian cấp văn bằng: 12–18 tháng'],
        link_text: 'Đăng ký ngay',
        link_url: '/dich-vu/nhan-hieu-trong-nuoc',
      },
      {
        title: 'Đăng Ký Nhãn Hiệu Quốc Tế',
        description: 'Bảo hộ nhãn hiệu tại các thị trường xuất khẩu qua hệ thống Madrid hoặc đăng ký trực tiếp.',
        features: ['Tư vấn chọn thị trường đăng ký phù hợp', 'Hệ thống Madrid — 1 đơn 100+ quốc gia', 'Theo dõi và gia hạn định kỳ'],
        link_text: 'Tư vấn quốc tế',
        link_url: '/dich-vu/nhan-hieu-quoc-te',
      },
      {
        title: 'Bản Quyền & Giải Quyết Tranh Chấp',
        description: 'Đăng ký bản quyền tác phẩm, xử lý vi phạm SHTT và đại diện khiếu nại tranh chấp.',
        features: ['Đăng ký bản quyền phần mềm, tác phẩm', 'Gửi thông báo vi phạm & yêu cầu gỡ bỏ', 'Đại diện khiếu nại tại NOIP/Tòa án'],
        link_text: 'Tư vấn miễn phí',
        link_url: '/dich-vu/ban-quyen',
      },
    ],
  },
  {
    acf_fc_layout: 'faq_accordion',
    section_label: 'FAQ Dịch Vụ',
    section_title: 'Câu Hỏi Về Dịch Vụ',
    section_desc: 'Những thắc mắc phổ biến khi sử dụng dịch vụ của chúng tôi',
    dark_background: false,
    faqs: [
      { question: 'Làm thế nào để biết loại hình doanh nghiệp nào phù hợp với tôi?', answer: 'Chúng tôi cung cấp buổi tư vấn miễn phí 30 phút để phân tích nhu cầu, ngành nghề, số thành viên và kế hoạch phát triển, từ đó tư vấn loại hình phù hợp nhất cho bạn.' },
      { question: 'Tôi có cần phải lên văn phòng hay không?', answer: 'Không bắt buộc. Toàn bộ quy trình có thể thực hiện online — tư vấn qua Zalo/Zoom, gửi tài liệu qua email, ký tên điện tử. Bạn chỉ cần đến khi cần ký giấy tờ pháp lý quan trọng nếu có yêu cầu.' },
      { question: 'Phí dịch vụ được tính như thế nào?', answer: 'Chúng tôi báo giá trọn gói theo từng dịch vụ cụ thể — bao gồm phí dịch vụ và lệ phí nhà nước. Không phát sinh chi phí ngoài báo giá ban đầu.' },
      { question: 'Sau khi thành lập công ty, tôi cần làm gì?', answer: 'Chúng tôi sẽ hướng dẫn đầy đủ: mở tài khoản ngân hàng, đăng ký chữ ký số, hóa đơn điện tử, khai báo thuế ban đầu và các thủ tục khác trong 30 ngày đầu hoạt động.' },
    ],
  },
  {
    acf_fc_layout: 'contact_form',
    section_label: 'Yêu Cầu Tư Vấn',
    section_title: 'Nhận Báo Giá & Tư Vấn Miễn Phí',
    dark_background: true,
  },
]
